// <auto-generated />
namespace ToTheMoon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class added_fields_to_spaces : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_fields_to_spaces));
        
        string IMigrationMetadata.Id
        {
            get { return "201405201548399_added_fields_to_spaces"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
