// <auto-generated />
namespace ToTheMoon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class nameconflicts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nameconflicts));
        
        string IMigrationMetadata.Id
        {
            get { return "201405291544442_name-conflicts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
